jobs:
- job: macOS
  host: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - template: .ci/build.yaml

- job: Linux
  host: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: .ci/build.yaml

- job: Windows
  host: Windows
  pool:
    vmImage: 'vs2017-win2016'
  sign: true  # Extra step on Windows only
  steps:
  - template: .ci/build.yaml

