parameters:
  host: ''
  pool: ''
  sign: false

jobs:
- job: ${{ parameters.host }}
  pool: ${{ parameters.pool }}
  steps:
  - ${{ if eq(parameters.sign, 'true') }}:
    - script: 'npm install -g esy@latest --unsafe-perm'
      displayName: 'Installing deps'
  - ${{ if eq(parameters.sign, 'false') }}:
    - script: 'sudo npm install -g esy@latest --unsafe-perm'
      displayName: 'Installing deps'
  - script: |
      mkdir -p test_dir
      cd test_dir
      echo $PWD
      echo '{"dependencies": {"@esy-packages/esy-openssl" : "esy-packages/esy-openssl:package.json#'$(git rev-parse --short HEAD)'"}}' > package.json
      cat package.json
      esy install
    displayName: 'Installing deps'
  - script: esy x which openssl
    displayName: 'Building and dry run'
